spring:
  application:
    name: recipeBook
  datasource:
    url: jdbc:postgresql://localhost:5432/recipebook
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    jpa:
      auditing:
        enabled: true

server:
  port: 8080
